CREATE DATABASE IF NOT EXISTS kalkulator CHARACTER SET utf8mb4 COLLATE utf8mb4_polish_ci;

USE kalkulator;

CREATE TABLE IF NOT EXISTS funkcje (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tresc VARCHAR(255) NOT NULL,
  data DATETIME DEFAULT CURRENT_TIMESTAMP
);
